#
# Copyright © 2016-2017 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

services:
  tb:
    image: "tempus/application:0.0.1"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683:5683/udp"
    env_file:
      - tb.env
    environment:
      - ADD_SCHEMA_AND_SYSTEM_DATA=${ADD_SCHEMA_AND_SYSTEM_DATA}
      - ADD_DEMO_DATA=${ADD_DEMO_DATA}
    links:
      - zk
      - kafka
    volumes:
      - "${HSQLDB_DATA_DIR}:/usr/share/thingsboard/data/sql"
    entrypoint: /run-application.sh
  postgres:
    image: "postgres:9.6"
    ports:
    - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
  zk:
    image: "tempus/zk:0.0.1"
    ports:
      - "2181"
  nifi:
    image: "tempus/nifi:0.0.1"
    ports:
    - "9090:8080"
    - "9191:9191"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "${POSTGRES_DATA_DIR}:/var/lib/postgresql/data"
  kafka:
    image: "tempus/kafka:0.0.1"
    ports:
      - "9092:9092"
    depends_on:
      - "zk"
    links:
      - "zk"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.159
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 16000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark-master:
    image: "tempus/spark-2:latest"
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_WEBUI_PORT: 8181
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8181:8181
    links:
      - kafka
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data
  spark-worker-1:
    image: "tempus/spark-2:latest"
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
      - kafka
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/tmp/data